name: Norminette Lint Check

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Norminette
        run: |
          pip install --upgrade pip
          pip install norminette
      - name: Run Norminette Linter
        run: |
          find . -type f \( -name \*.c -o -name \*.h \) -not -type d \( -name tests -o -name docs \) -exec sh -c 'norminette {}' \; | tee output
          echo "NORME_ERRORS=$(grep -E 'Error|Warning' output | wc -l)" >> $GITHUB_ENV
      - name: Verify Results
        run: |
          echo "Norminette results: $NORME_ERRORS errors."
          [[ $NORME_ERRORS == 0 ]]
